version: '3.1'

services:
  client:
    container_name: client
    build: ./Client
    restart: unless-stopped
    ports:
      - ${CLIENT_HOST_PORT}:{CONTAINER_PORT}

  counter_app:
    container_name: counter_app
    build: ./CounterApp
    restart: unless-stopped
    ports:
      - ${COUNTER_APP_HOST_PORT}:{CONTAINER_PORT}